RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-LibreChat
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: true
  Type: String
  AssociationProperty: ALIYUN::ECS::Instance::Password
  Label: QWEN_API_KEY
  Name: QWEN_API_KEY
DockerComposeYamlPath: docker-compose.yml
Owner: linziqiaolzq
Branch: main
Platform: github
