Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
    - TemplateName: ECS单机版
      SupportOperations:
      - Start
      - Stop
      - Restart
    SupportBackup: true
    ModifyParametersConfig:
    - TemplateName: ECS单机版
      Operation:
      - Name: 变更ECS实例规格
        Description: 变更ECS实例规格
        Type: Custom
        Parameters:
        - EcsInstanceType
      - Name: 变更ECS实例密码
        Description: 变更ECS实例密码
        Type: Custom
        Parameters:
        - InstancePassword
    ParameterConfigs:
    - TemplateName: 'ECS单机版'
      Parameters:
        QWEN_API_KEY:
          Type: String
          Label: （选填）通义千问API Key
          Default: ''
      Metadata:
        ParameterGroups:
        - Parameters:
          - QWEN_API_KEY
          DefaultEnvFilePath: .env
          Formatter: env
          Name: Default
  UpgradeMetadata:
    Description: 升级
    SupportUpgradeFromVersions: []
    SupportRollback: true
    UpgradeComponents:
    - Configuration
    - Resource
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
        - ap-southeast-1
      ArtifactRelation:
        ecs_image_quickstart-LibreChat:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
    - Name: ECS单机版
      Url: 'ros_templates/template.yaml'
      ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
      AllowedRegions:
      - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
  - Locale: zh-CN
    Name: LibreChat社区版
    ShortDescription: LibreChat 是一个开源的聊天应用程序，旨在提供用户友好的交流体验。它支持多种功能，包括实时消息传递、文件共享以及集成各种第三方服务。LibreChat 以隐私和安全为重点，确保用户的数据不被滥用或收集。
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/bfd30cc4-e959-4093-b5cb-77a05058b911.png
    Softwares:
      - Name: librechat
        Version: 0.7.9
        Locale: zh-CN
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-LibreChat
    Description: quickstart-LibreChat EcsImage
    SupportRegionIds:
    - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: workhardliuzheng
        RepoName: aliyun-computenest/quickstart-LibreChat
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/meili_data_v1.12" ]; then cp -r "/root/code/meili_data_v1.12" "/root/application/"; fi
        if [ -e "/root/code/images" ]; then cp -r "/root/code/images" "/root/application/"; fi
        if [ -e "/root/code/docker-compose.yml" ]; then cp -r "/root/code/docker-compose.yml" "/root/application/"; fi
        if [ -e "/root/code/data-node" ]; then cp -r "/root/code/data-node" "/root/application/"; fi
        if [ -e "/root/code/logs" ]; then cp -r "/root/code/logs" "/root/application/"; fi
        if [ -e "/root/code/uploads" ]; then cp -r "/root/code/uploads" "/root/application/"; fi
        if [ -e "/root/code/.env" ]; then cp -r "/root/code/.env" "/root/application/"; fi
        if [ -e "/root/code/pgdata2" ]; then cp -r "/root/code/pgdata2" "/root/application/"; fi
        if [ -e "/root/code/librechat.yaml" ]; then cp -r "/root/code/librechat.yaml" "/root/application/"; fi
        cd /root/application
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' docker-compose.yml
        docker compose -f docker-compose.yml build 
        docker compose -f docker-compose.yml pull 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded' || true;
